# Generated by Django 3.1.3 on 2020-11-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
    ]
